services:
  user-services-app:
    build: .
    ports:
      - 8080:8080

    depends_on:
      - database

    networks:
      - user-services

  database:
    image: "postgres"
    ports:
      - 5432:5432

    networks:
      - user-services

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123 
      POSTGRES_DB: user_manager

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8888:80

    networks:
      - user-services

    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123
      MAX_LOGIN_ATTEMPTS: 100

networks:
  user-services: 
    driver: bridge