apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-app
  labels:
    app: user-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager-app
  template:
    metadata:
      labels:
        app: user-manager-app
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
        - name: user-manager-app
          image: 343218189535.dkr.ecr.us-east-1.amazonaws.com/user-manager-app-jayamal:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: usermanager-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  type: NodePort
  selector:
    app: user-manager-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: microk8s-hostpath

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: init-script-vol
          configMap:
            name: pg-init-script
        - name: pg-data-vol
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: PGDATA
              value: /var/lib/postgres/18/docker/data
            - name: POSTGRES_DB
              value: user_manager
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: usermanager-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: pg-data-vol
              mountPath: /var/lib/postgresql
              subPath: 18-data
            - name: init-script-vol
              mountPath: /docker-entrypoint-initdb.d/schema.sql
              subPath: schema.sql

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
              
